#include <iostream>
#include <ctime>
#include <vector>
#include <cmath>
#include <cstdlib>

void set_random_seed();
int randn(int n);
void duplicate(const std::vector<int>& attempt, const std::vector<int>& temp, int& black2, int& white2, int num);
void change(std::vector<int>& attempt, int num, int length, int x);

struct mm_code_maker
{
  void init(int i_length, int i_num)
  {
      length = i_length;
      num = i_num;
    }

    void generate_sequence()
    {
        for(int i = 0; i < length; i++)
        {
          sequence.push_back(randn(num));
        }
    }

    void give_feedback(const std::vector<int>& attempt, int& black_hits, int& white_hits)
    {
        black_hits = 0;
        for (int i = 0; i < attempt.size(); i++)
        {
          if (attempt[i] == sequence[i])
          {
            black_hits++;
          }
        }
        int combined = 0;
        for (int j = 0; j < num; j++)
        {
          int seq = 0;
          int att = 0;
          for (int i = 0; i < attempt.size(); i++)
          {
            if (attempt[i] == j)
            {
              att++;
            }
            if (sequence[i] == j)
            {
              seq++;
            }
          }
          if (seq > att)
            {
              combined = combined + att;
            }
          else if (seq <= att)
            {
              combined = combined + seq;
            }
        }
        white_hits = combined - black_hits;
    }
    std::vector<int> sequence;

    int length;
    int num;
};

struct mm_solver
{
    void init(int i_length, int i_num)
    {
        length = i_length;
        num = i_num;
        int x = std::pow(num, length);
        for (int i = 0; i < x; i++)
        {
          vector.push_back(i);
        }
    }

    void create_attempt(std::vector<int>& attempt)
    {
        unsigned x = randn(vector.size());
        change(attempt, num, length, vector[x]);
    }

    void learn(std::vector<int>& attempt, int black_hits, int white_hits)
    {
      std::vector<int> temp;
      int white2 = 0;
      int black2 = 0;

      for (int i = 0; i < vector.size(); i++)
      {
        std::vector<int> temp2;

        change(temp2, num, length, vector[i]);
        duplicate(attempt, temp2, black2, white2, num);

        if (black_hits == black2 && white_hits == white2)
        {
          temp.push_back(vector[i]);
        }
      }
      vector = temp;
    }
    std::vector<int> vector;
    int length;
    int num;
};
int main()
{
  high_resolution_clock::time_point t1 = high_resolution_clock::now();
    set_random_seed();

    float length, num, total_game = 1000, total_attempt = 0, max=0;
    std::vector<int> worse;
    float average;
    std::cout << "enter length of sequence and number of possible values:" << std::endl;
    std::cin >> length >> num;

    for(int k=0; k < total_game; k++){
			std::cout << "game number: " << k << '\n';
      mm_solver solver;
      solver.init(length, num);
      mm_code_maker maker;
      maker.init(length, num);
      maker.generate_sequence();
      std::cout << "generate_sequence" << '\n';
      std::cout << "the sequence generated by the code maker was:" << std::endl;
      for(int i = 0; i < maker.sequence.size(); i++){
          std::cout << maker.sequence[i] << " ";
      }
      std::cout << std::endl;
      int black_hits=0, white_hits=0;
      int attempts_limit = 20;
      int attempts = 0;
      while((black_hits < length) && (attempts < attempts_limit)){
          std::vector<int> attempt;
          solver.create_attempt(attempt);
          maker.give_feedback(attempt, black_hits, white_hits);
          std::cout << "attempt number " << attempts << " : " <<std::endl;
          for(int i = 0; i < attempt.size(); i++){
              std::cout << attempt[i] << " ";
          }
          std::cout << std::endl;
          std::cout << "black pegs: " << black_hits << " " << " white pegs: " << white_hits << std::endl;
          solver.learn(attempt, black_hits, white_hits);
          attempts++;
      }

      if(black_hits == length){
          std::cout << "the solver has found the sequence in " << attempts << " attempts" << std::endl;
          total_attempt = total_attempt+attempts;
      }
      else{
          std::cout << "after " << attempts << " attempts still no solution" << std::endl;
      }
      if(attempts > max){
        max = attempts;
        worse = maker.sequence;
      }
    }
    high_resolution_clock::time_point t2 = high_resolution_clock::now();
    auto duration = duration_cast<milliseconds>( t2 - t1 ).count();
    average = total_attempt/total_game;
    std::cout << "average is " << average << '\n';
//    std::cout << "worst attempts: " << max << '\n';
//    std::cout << "out of " << total_attempt << '\n';
//    std::cout << "time elapsed:" << duration << '\n';
    std::cout << "average time per game: " << duration/total_game << '\n';
    return 0;
}
void set_random_seed()
{
  std::srand(std::time(0));
}
int randn(int n)
{
  return std::rand() % n;
}

void duplicate(const std::vector<int>& attempt, const std::vector<int>& temp, int& black2, int& white2, int num)
{
  black2 = 0;
  white2 = 0;
  int att2;
  int seq2;
  for (int i = 0; i < attempt.size(); i++)
  {
    if (attempt[i] == temp[i])
    {
      black2++;
    }
  }
  int combined2 = 0;
  for (int j = 0; j <= num; j++)
  {
    att2 = 0;
    seq2 = 0;
    for (int i = 0; i < attempt.size(); i++)
    {
      if (temp[i] == j)
      {
        seq2++;
      }
      if (attempt[i] == j)
      {
        att2++;
      }
    }
    if (seq2 > att2)
      {
        combined2 = combined2 + att2;
      }
    else if (seq2 <= att2)
      {
        combined2 = combined2 + seq2;
      }
  }
  white2 = combined2 - black2;
}

void change(std::vector<int>& attempt, int num, int length, int x)
{
  while (x > 0)
  {
    attempt.insert(attempt.begin(), x % num);
    x = x / num;
  }
  while (attempt.size() < length)
  {
    attempt.insert(attempt.begin(), 0);
  }
}
